---
title: "Compare Factgrid and Wikidata"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---


```{r setup, include=FALSE}
library(tidyverse)
library(glue)
library(SPARQL)
library(kabrutils)
library(here)
library(flexdashboard)
library(WikidataR)
library(shinyjs)
config_file <- "data-publishing/factgrid/config.yml"
config <- yaml::read_yaml(here(config_file))
```


```{r fetch_available_properties}

#' Get properties related to persons
#' @return dataframe
get_person_properties <- function() {
  tmp <- readr::read_file("https://raw.githubusercontent.com/cutterkom/remove-na-lgbtiq-queer-knowledge-graph/main/data-publishing/factgrid/queries/get_all_properties_person_with_corresponding_prop.rq") %>% 
  sparql_to_tibble(endpoint = config$connection$sparql_endpoint) %>% 
  mutate(
    fg_property_id = str_extract(fg_property, "P[0-9]+"),
    wd_property_id = str_extract(wd_property, "P[0-9]+"),
    label = paste0(fg_propertyLabel, " (FG: ", fg_property_id, ", WD: ", wd_property_id, ")"),
    label = str_remove_all(label, '"|@en')
    ) 
    
  return(tmp)
}
```

Refering to Persons
=====================================  
 {.sidebar}
-------------------------------------

Which property should be compared?

```{r}
persons_properties <- get_person_properties()

persons_properties_list  <- persons_properties %>% 
  select(label, fg_property_id) %>% 
  deframe()

checkboxGroupInput("person_properties", label = "Properties available that refer to persons", choices = persons_properties_list)

actionButton("button_start_person_properties", "Submit", class = "btn-primary")
```

Please be patient, it may take a few moments if a lot of data is requested... 

```{r}


#' Get comparison data based on property
#' 
#' This functions queries data on Factgrid looking for properties related to persons that have a corresponding Wikidata property. Utilizes federated queries.
#' @param input chosen properties in input$person_properties
#' @return dataframe
get_comparison <- function(input) {
  persons_properties %>% 
    filter(fg_property_id %in% input) %>% 
    pmap_dfr(function(...) {
      current <- tibble(...)
      cli::cli_alert_info("Fetch data for: {current$fg_propertyLabel}")
      fg_property_id <- current$fg_property_id
      
      query <- paste0( '
      #defaultView:Table
      
      # Prefix standard 
      # Factgrid
      PREFIX fg: <https://database.factgrid.de/entity/>
      PREFIX fgt: <https://database.factgrid.de/prop/direct/>
      
      # Wikidata
      PREFIX wdt: <http://www.wikidata.org/prop/direct/>
      PREFIX wd: <http://www.wikidata.org/entity/>
      # misc
      PREFIX wikibase: <http://wikiba.se/ontology#>
      PREFIX bd: <http://www.bigdata.com/rdf#>
      PREFIX schema: <http://schema.org/>
      
      SELECT DISTINCT ?fg_item ?fg_itemLabel ?wd_item ?fg_property ?fg_propertyLabel ?wd_property ?fg_value ?fg_valueLabel ?wd_value_from_fg ?wd_value_from_wd ?is_same where {
      
        # labels from Factgrid
        SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }  
      
        # starting points
        # which property in focus?
        # todo in one var
        BIND(fgt:', fg_property_id, ' as ?fg_property)
        BIND(fg:', fg_property_id, ' as ?fg_property_as_item)
        # set property of corresponding wikidata property; is constant
        BIND(fgt:P343 as ?fg_corr_wd)
      
        # transform wikidata qid in factgrid to wikidata entity iri
        ?link schema:about ?fg_item .
        ?link schema:isPartOf <https://www.wikidata.org/> . 
        ?link schema:name ?qid.
        BIND(IRI(CONCAT(STR(wd:), ?qid)) AS ?wd_item)
      
        # get corresponding wikidata property
        # and store as IRI
        ?fg_property_as_item ?fg_corr_wd ?fg_corr_wd_value .
        BIND(IRI(CONCAT(STR(wdt:), ?fg_corr_wd_value)) AS ?wd_property)
      
        # get factgrid statement
        ?fg_item ?fg_property ?fg_value .
        # get wikidata qid of fg_value
        # used later for comparison
        ?link_value schema:about ?fg_value .
        ?link_value schema:isPartOf <https://www.wikidata.org/> . 
        ?link_value schema:name ?qid_value.
        BIND(IRI(CONCAT(STR(wd:), ?qid_value)) AS ?wd_value_from_fg)
      
        # now change to wikidata as data source
        # get value from wikidata
        SERVICE <https://query.wikidata.org/sparql> {
            OPTIONAL {
                ?wd_item ?wd_property ?wd_value_from_wd.
         }
        }
        BIND (IF(?wd_value_from_fg = ?wd_value_from_wd, "true", "false") AS ?is_same)
      }
      
      ')
      
      sparql_to_tibble(query, endpoint = config$connection$sparql_endpoint) %>% 
        mutate(
          fg_property_id = str_extract(fg_property, "P[0-9]+"),
          wd_property_id = str_extract(wd_property, "P[0-9]+"))
     
    })
  
}

```


```{r}
comparison_raw <- eventReactive(input$button_start_person_properties, {
    get_comparison(input$person_properties)
  })

```

Properties you asked for:  {data-height=70}
-------------------------------------

```{r}
### Properties to compare:
# render_properties_in_action <- reactive({
#   persons_properties %>% 
#     filter(fg_property_id %in% input$person_properties) %>% 
#     pull(label) %>% 
#     glue::glue_collapse(., sep = ", ", last = "")
# })
# 
# renderText({render_properties_in_action() })
```

### in both {.value-box}

```{r}
in_both_nrow <- reactive({
  nrow(in_both())
})

renderValueBox({
  valueBox(
    value = in_both_nrow(),
    icon = "fa-area-chart"
  )
})
```

### only in Factgrid {.value-box}

```{r}
only_in_fg_nrow <- reactive({
  nrow(only_in_fg())
})

renderValueBox({
  valueBox(
    value = only_in_fg_nrow(),
    icon = "fa-area-chart"
  )
})
```

### only in Wikidata {.value-box}

```{r}
only_in_wd_nrow <- reactive({
  nrow(only_in_wd())
})

renderValueBox({
  valueBox(
    value = only_in_wd_nrow(),
    icon = "fa-area-chart"
  )
})
```


Row {.tabset .tabset-fade}
-------------------------------------
   
### Both, in Factgrid and Wikidata

```{r show_data_in_both}
in_both <- reactive({
  data <- comparison_raw() %>% 
    filter(is_same == "true") %>% 
    distinct(fg_item, fg_itemLabel, fg_property_id, fg_valueLabel, wd_value_from_fg, wd_value_from_wd) %>% 
    left_join(persons_properties %>% select(fg_property_id, fg_propertyLabel), by = "fg_property_id")
  })


renderTable({
  in_both()  %>% 
    select(fg_itemLabel, fg_propertyLabel, fg_valueLabel)
  })
```

### Only in Factgrid

```{r}
only_in_fg <-  reactive({
  
  data <- comparison_raw() %>% 
    filter(is.na(is_same)) %>% 
    distinct(fg_item, fg_itemLabel, fg_property_id, fg_valueLabel, wd_value_from_fg) %>% 
    # remove those that are present in wd
    anti_join(in_both(), by = c("fg_item", "wd_value_from_fg")) %>% 
    left_join(persons_properties %>% select(fg_property_id, fg_propertyLabel), by = "fg_property_id")
  
  })

renderTable({only_in_fg()  %>% 
    select(fg_itemLabel, fg_propertyLabel, fg_valueLabel)})


```

```{r wikidata_not_working}
actionButton("button_import_wikidata", "Submit", class = "btn-primary")
import_in_wikidata <- reactive({
  import <- comparison_raw() %>% 
    inner_join(only_in_fg() %>% distinct(fg_item, wd_value_from_fg), by = c("fg_item", "wd_value_from_fg")) %>% 
    mutate(
      wd_item_id = str_extract(wd_item, "Q[0-9]+"),
      wd_value_from_fg_id = str_extract(wd_value_from_fg, "Q[0-9]+")
      ) %>% 
    select(item = wd_item_id, property = wd_property_id, value = wd_value_from_fg_id) 
  print(import)
  
  WikidataR::write_wikidata(
    items = import$item,
    properties = import$property,
    values = import$value,
    format = "website"
  )
})

useShinyjs()
actionButton("showtxt", "Show/Download File")

 observeEvent(input$showtxt,{
        # Write some text
        write.table(c("Test"), file = "www/test.txt")
      })


      # Call Onclick
      #onclick("showtxt", runjs("window.open('test.txt')"))
  onclick("showtxt", runjs('window.open("http://google.com", "Google", "width=480,height=360,resizable=no,toolbar=no,menubar=no,location=no,status=no'))
 
# 
# shiny::actionButton(inputId='ab1', label="Learn More", 
#                           icon = icon("th"), 
#                           onclick =paste0("window.open('", import_in_wikidata(), "', '_blank')"))

# eventReactive(input$button_import_wikidata, {
#   im <- import_in_wikidata()
#    WikidataR::write_wikidata(
#     items = im$item,
#     properties = im$property,
#     values = im$value,
#     format = "api",
#     submit = FALSE
#   )
# })

```


### Only in Wikidata

```{r}
only_in_wd <- reactive({
  
  data <- comparison_raw() %>% 
    filter(is_same == "false") %>% 
    distinct(fg_item, fg_itemLabel, fg_property_id, wd_value_from_wd) %>% 
    # remove those that are present in wd
    anti_join(in_both(), by = c("fg_item", "wd_value_from_wd")) %>% 
    left_join(persons_properties %>% select(fg_property_id, fg_propertyLabel), by = "fg_property_id")
  
  })

renderTable({only_in_wd()  %>% 
    select(fg_itemLabel, fg_propertyLabel, wd_value_from_wd)})
```

