---
title: "Authors and VIAF"
output: html_notebook
---


```{r}
library(tidyverse)
library(kabrutils)
con <- connect_db()
DBI::dbExecute(con, "set names utf8;")
authors <- tbl(con, "authors") %>% 
  left_join(tbl(con, "authors_viaf_gnd"), by = "id") %>% 
  select(-contains("_at")) %>% 
  collect() %>% 
  mutate(has_viaf_id = ifelse(!is.na(viaf_id), 1, 0))
DBI::dbDisconnect(con); rm(con)

```

Welche Autoren haben eine VIAF-ID?

```{r}
authors %>% 
  count(has_viaf_id)
  
```

Beispiel: `Napoleon Seyfahrt` wird nicht gefunden

Aber: 

* https://de.wikipedia.org/wiki/Napoleon_Seyfarth
* inkl VIAF ID

```{r}
library(viafr)
viaf_suggest("Edmund White")
viaf_suggest("Edmund White")
```

```{r}
library(libbib)
con <- connect_db()
DBI::dbExecute(con, "set names utf8;")
books <- tbl(con, "books") %>% 
  left_join(tbl(con, "book_author"), by = c("id" = "book_id")) %>% 
  left_join(tbl(con, "authors"), by = c("author_id" = "id"),  suffix = c("_book", "_author")) %>% 
  collect()
DBI::dbDisconnect(con); rm(con)


```

ISBN normalisieren

```{r}
books <- books %>% 
  mutate(isbn_norm = normalize_isbn(isbn),
         diff = isbn_norm == isbn)
normalize_isbn_13(books$isbn)

check_isbn <- books %>% 
  filter(!is.na(isbn_norm)) %>% 
  head(20) %>% 
  mutate(check_isbn = map(.x = isbn_norm, .f = check_lobid_item, "isbn")) %>% 
  unnest(col = "check_isbn")
```

